import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderNav from "@/components/modules/header-nav";
import Footer from "@/components/modules/footer";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "flex flex-col justify-between min-h-screen",
        )}
      >
        <HeaderNav />
        <section className="grid-cols-12">{children}</section>
        <Footer />
      </body>
    </html>
  );
}
